// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfitjscyangnyohfrexk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmaXRqc2N5YW5nbnlvaGZyZXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzI4OTEsImV4cCI6MjA2NTE0ODg5MX0.hEr7J4k1KgkL9TwD48UBl3VrQmJGHoqA2I-8wA1EWEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);